<a href="https://colab.research.google.com/github/ManojKumarTiwari/Pytorch/blob/master/1_PytorchBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
x = torch.Tensor([2,3])
y = torch.Tensor([5,2])

In [0]:
x, y

(tensor([2., 3.]), tensor([5., 2.]))

In [0]:
t = print(x * y)

tensor([10.,  6.])


In [0]:
z = torch.zeros(2,5)
z

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [0]:
r = torch.rand(2,4)
r

tensor([[0.5553, 0.6962, 0.1463, 0.4648],
        [0.2930, 0.4715, 0.5697, 0.3292]])

In [0]:
r.shape

torch.Size([2, 4])

In [0]:
r.view([1,8])

tensor([[0.5553, 0.6962, 0.1463, 0.4648, 0.2930, 0.4715, 0.5697, 0.3292]])

In [0]:
r.view([8,1])

tensor([[0.5553],
        [0.6962],
        [0.1463],
        [0.4648],
        [0.2930],
        [0.4715],
        [0.5697],
        [0.3292]])

In [0]:
r

tensor([[0.5553, 0.6962, 0.1463, 0.4648],
        [0.2930, 0.4715, 0.5697, 0.3292]])

In [0]:
r = r.view([1,8])

In [0]:
r

tensor([[0.5553, 0.6962, 0.1463, 0.4648, 0.2930, 0.4715, 0.5697, 0.3292]])